### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by cmolinan** [cmolinan/Catalog-of-my-things#35]
Kanban board link -> https://github.com/cmolinan/Catalog-of-my-things/projects/1

We are three persons team.

Team member #1:  https://github.com/cmolinan
Team member #2: https://github.com/angeluray
Team member #3:  https://github.com/Kumilachew-g

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @cmolinan, @Kumilachew-g and @angeluray,

Good job so far!
✔️ Kanban columns are well created
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Some of your tasks do not have descriptions. See the example below. Kindly ensure all your tasks have appropriate descriptions.

  ![djdw](https://user-images.githubusercontent.com/36542986/201738445-337a672c-1a2d-42de-a122-c08572cc198c.jpg)

- [ ] This task is not assigned to anyone. Kindly fix that.

  ![dkde](https://user-images.githubusercontent.com/36542986/201738439-21ab936f-cd64-4585-8833-23355fdada75.jpg)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Kumilachew-g** [comment]
Done based on review. Thanks!!!

**Comment by prolajumokeoni** [comment]
Hi @Team

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- Good board setup 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by cmolinan** [comment]
@prolajumokeoni Thanks for your review !
